# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    acl: 'puppetlabs/acl' # used by puppet_run_scheduler
    archive: 'puppet/archive'
    cron: 'puppetlabs/cron_core' # used by puppet_run_scheduler
    # puppet_run_scheduler: 'reidmv/puppet_run_scheduler'
    scheduled_task: 'puppetlabs/scheduled_task' # used by puppet_run_scheduler
    stdlib: 'puppetlabs/stdlib'
  repositories:
    puppet_run_scheduler: https://github.com/reidmv/reidmv-puppet_run_scheduler.git